// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ArticleArchieveDocumentDataSlicesSlice =
  | TitleAndRichTextSlice
  | RichTextSlice;

/**
 * Content for Article archieve documents
 */
interface ArticleArchieveDocumentData {
  /**
   * title field in *Article archieve*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_archieve.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *Article archieve*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_archieve.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Slice Zone field in *Article archieve*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article_archieve.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ArticleArchieveDocumentDataSlicesSlice> /**
   * Meta Title field in *Article archieve*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article_archieve.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article archieve*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article_archieve.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article archieve*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_archieve.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article archieve document from Prismic
 *
 * - **API ID**: `article_archieve`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleArchieveDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ArticleArchieveDocumentData>,
    "article_archieve",
    Lang
  >;

/**
 * Content for Article Posts documents
 */
interface ArticlePostsDocumentData {
  /**
   * Cover image field in *Article Posts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article_posts.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Title field in *Article Posts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_posts.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Date field in *Article Posts*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article_posts.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Excerpt field in *Article Posts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A short description
   * - **API ID Path**: article_posts.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Content field in *Article Posts*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article_posts.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Article Posts document from Prismic
 *
 * - **API ID**: `article_posts`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticlePostsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticlePostsDocumentData>,
    "article_posts",
    Lang
  >;

/**
 * Item in *footer → Quick Links*
 */
export interface FooterDocumentDataQuickLinksItem {
  /**
   * Link field in *footer → Quick Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.quick_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *footer → Contact Info*
 */
export interface FooterDocumentDataContactInfoItem {
  /**
   * Info field in *footer → Contact Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Gmail, Location, Phone Number, Etc
   * - **API ID Path**: footer.contact_info[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;
}

/**
 * Item in *footer → Socials*
 */
export interface FooterDocumentDataSocialsItem {
  /**
   * Social Icon field in *footer → Socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[].social_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_icon: prismic.ImageField<never>;
}

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Quick Links field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.quick_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  quick_links: prismic.GroupField<Simplify<FooterDocumentDataQuickLinksItem>>;

  /**
   * Contact Info field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact_info[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact_info: prismic.GroupField<Simplify<FooterDocumentDataContactInfoItem>>;

  /**
   * Socials field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<FooterDocumentDataSocialsItem>>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | BannerSliceSlice
  | SideBySideInfoSlice
  | LocationSliceSlice
  | TitleAndRichTextSlice
  | HeroReviewSlice
  | HeroTestimonialsSlice
  | HeroSliceSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Nav → Navlinks*
 */
export interface NavbarDocumentDataNavlinksItem {
  /**
   * Link field in *Nav → Navlinks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navlinks[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type NavbarDocumentDataSlicesSlice = LinkSectionSlice;

/**
 * Content for Nav documents
 */
interface NavbarDocumentData {
  /**
   * Logo field in *Nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Search icon field in *Nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.search_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  search_icon: prismic.ImageField<never>;

  /**
   * Navlinks field in *Nav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navlinks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navlinks: prismic.GroupField<Simplify<NavbarDocumentDataNavlinksItem>>;

  /**
   * Slice Zone field in *Nav*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavbarDocumentDataSlicesSlice>;
}

/**
 * Nav document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TestimonialAboutSlice
  | FormSlice
  | SideBySideInfoSlice
  | LinkSectionSlice
  | OurTeamSliceSlice
  | AlternateGridSlice
  | LocationSliceSlice
  | TitleAndRichTextSlice
  | HeroReviewSlice
  | HeroTestimonialsSlice
  | HeroSliceSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Testimonial title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.testimonial_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Testimonial Cards documents
 */
interface TestimonialCardsDocumentData {
  /**
   * image field in *Testimonial Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Testimonial Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Testimonial Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Full description field in *Testimonial Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards.full_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  full_description: prismic.KeyTextField;

  /**
   * isButton field in *Testimonial Cards*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: testimonial_cards.isbutton
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isbutton: prismic.BooleanField;

  /**
   * Button field in *Testimonial Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Testimonial Cards document from Prismic
 *
 * - **API ID**: `testimonial_cards`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialCardsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialCardsDocumentData>,
    "testimonial_cards",
    Lang
  >;

type TreatmentBlogDocumentDataSlicesSlice =
  | RichTextSlice
  | TitleAndRichTextSlice
  | HeroSliceSlice;

/**
 * Content for Treatment blog documents
 */
interface TreatmentBlogDocumentData {
  /**
   * Title field in *Treatment blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Treatment blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TreatmentBlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Treatment blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: treatment_blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Treatment blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: treatment_blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Treatment blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Treatment blog document from Prismic
 *
 * - **API ID**: `treatment_blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TreatmentBlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TreatmentBlogDocumentData>,
    "treatment_blog",
    Lang
  >;

export type AllDocumentTypes =
  | ArticleArchieveDocument
  | ArticlePostsDocument
  | FooterDocument
  | HomepageDocument
  | NavbarDocument
  | PageDocument
  | TestimonialCardsDocument
  | TreatmentBlogDocument;

/**
 * Primary content in *AlternateGrid → Default → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
  /**
   * Image field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Body field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternateGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AlternateGrid → Image Left → Primary*
 */
export interface AlternateGridSliceImageLeftPrimary {
  /**
   * Image field in *AlternateGrid → Image Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Body field in *AlternateGrid → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageLeft.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Image Left variation for AlternateGrid Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<AlternateGridSliceImageLeftPrimary>,
  never
>;

/**
 * Primary content in *AlternateGrid → TitleAndButton → Primary*
 */
export interface AlternateGridSliceTitleAndButtonPrimary {
  /**
   * Image field in *AlternateGrid → TitleAndButton → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.titleAndButton.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *AlternateGrid → TitleAndButton → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.titleAndButton.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *AlternateGrid → TitleAndButton → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.titleAndButton.primary.body
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  body: prismic.KeyTextField;

  /**
   * Button field in *AlternateGrid → TitleAndButton → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.titleAndButton.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * TitleAndButton variation for AlternateGrid Slice
 *
 * - **API ID**: `titleAndButton`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceTitleAndButton = prismic.SharedSliceVariation<
  "titleAndButton",
  Simplify<AlternateGridSliceTitleAndButtonPrimary>,
  never
>;

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation =
  | AlternateGridSliceDefault
  | AlternateGridSliceImageLeft
  | AlternateGridSliceTitleAndButton;

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSlice = prismic.SharedSlice<
  "alternate_grid",
  AlternateGridSliceVariation
>;

/**
 * Primary content in *BannerSlice → Default → Primary*
 */
export interface BannerSliceSliceDefaultPrimary {
  /**
   * Left side illustration field in *BannerSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_slice.default.primary.left_side_illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  left_side_illustration: prismic.ImageField<never>;

  /**
   * right side illustration field in *BannerSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner_slice.default.primary.right_side_illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  right_side_illustration: prismic.ImageField<never>;
}

/**
 * Default variation for BannerSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BannerSlice*
 */
type BannerSliceSliceVariation = BannerSliceSliceDefault;

/**
 * BannerSlice Shared Slice
 *
 * - **API ID**: `banner_slice`
 * - **Description**: BannerSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceSlice = prismic.SharedSlice<
  "banner_slice",
  BannerSliceSliceVariation
>;

/**
 * Primary content in *Form → Default → Primary*
 */
export interface FormSliceDefaultPrimary {
  /**
   * Name field in *Form → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Surname field in *Form → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.surname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  surname: prismic.KeyTextField;

  /**
   * Email field in *Form → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * Message field in *Form → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.message
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  message: prismic.KeyTextField;

  /**
   * Button text field in *Form → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;

/**
 * Item in *HeroReview → Default → Primary → Review Cards*
 */
export interface HeroReviewSliceDefaultPrimaryReviewCardsItem {
  /**
   * Review Text field in *HeroReview → Default → Primary → Review Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_review.default.primary.review_cards[].review_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  review_text: prismic.KeyTextField;

  /**
   * Reviewers Name field in *HeroReview → Default → Primary → Review Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_review.default.primary.review_cards[].reviewers_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reviewers_name: prismic.KeyTextField;

  /**
   * Card Color field in *HeroReview → Default → Primary → Review Cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_review.default.primary.review_cards[].card_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_color: prismic.SelectField<"Purple " | "Pink" | "Green" | "Yellow">;
}

/**
 * Primary content in *HeroReview → Default → Primary*
 */
export interface HeroReviewSliceDefaultPrimary {
  /**
   * Title field in *HeroReview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_review.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Review Cards field in *HeroReview → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_review.default.primary.review_cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  review_cards: prismic.GroupField<
    Simplify<HeroReviewSliceDefaultPrimaryReviewCardsItem>
  >;
}

/**
 * Default variation for HeroReview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroReviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroReviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroReview*
 */
type HeroReviewSliceVariation = HeroReviewSliceDefault;

/**
 * HeroReview Shared Slice
 *
 * - **API ID**: `hero_review`
 * - **Description**: HeroReview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroReviewSlice = prismic.SharedSlice<
  "hero_review",
  HeroReviewSliceVariation
>;

/**
 * Primary content in *HeroSlice → Default → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Hero Video field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.hero_video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_video: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Logo field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * CTA Button field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSlice → image left and text right → Primary*
 */
export interface HeroSliceSliceImageLeftAndTextRightPrimary {
  /**
   * Image field in *HeroSlice → image left and text right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageLeftAndTextRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *HeroSlice → image left and text right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageLeftAndTextRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *HeroSlice → image left and text right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageLeftAndTextRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * CTA Button field in *HeroSlice → image left and text right → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageLeftAndTextRight.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * image left and text right variation for HeroSlice Slice
 *
 * - **API ID**: `imageLeftAndTextRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceImageLeftAndTextRight = prismic.SharedSliceVariation<
  "imageLeftAndTextRight",
  Simplify<HeroSliceSliceImageLeftAndTextRightPrimary>,
  never
>;

/**
 * Primary content in *HeroSlice → Image top text below → Primary*
 */
export interface HeroSliceSliceImageTopTextBelowPrimary {
  /**
   * Image field in *HeroSlice → Image top text below → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageTopTextBelow.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *HeroSlice → Image top text below → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageTopTextBelow.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *HeroSlice → Image top text below → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageTopTextBelow.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Add Button field in *HeroSlice → Image top text below → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_slice.imageTopTextBelow.primary.add_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  add_button: prismic.BooleanField;

  /**
   * CTA Button field in *HeroSlice → Image top text below → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageTopTextBelow.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * Image top text below variation for HeroSlice Slice
 *
 * - **API ID**: `imageTopTextBelow`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceImageTopTextBelow = prismic.SharedSliceVariation<
  "imageTopTextBelow",
  Simplify<HeroSliceSliceImageTopTextBelowPrimary>,
  never
>;

/**
 * Primary content in *HeroSlice → image bottom text top → Primary*
 */
export interface HeroSliceSliceImageBottomTextTopPrimary {
  /**
   * Title field in *HeroSlice → image bottom text top → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageBottomTextTop.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *HeroSlice → image bottom text top → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageBottomTextTop.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Image field in *HeroSlice → image bottom text top → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageBottomTextTop.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * image bottom text top variation for HeroSlice Slice
 *
 * - **API ID**: `imageBottomTextTop`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceImageBottomTextTop = prismic.SharedSliceVariation<
  "imageBottomTextTop",
  Simplify<HeroSliceSliceImageBottomTextTopPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation =
  | HeroSliceSliceDefault
  | HeroSliceSliceImageLeftAndTextRight
  | HeroSliceSliceImageTopTextBelow
  | HeroSliceSliceImageBottomTextTop;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

/**
 * Primary content in *HeroTestimonials → Default → Primary*
 */
export interface HeroTestimonialsSliceDefaultPrimary {
  /**
   * Title field in *HeroTestimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for HeroTestimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroTestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroTestimonials*
 */
type HeroTestimonialsSliceVariation = HeroTestimonialsSliceDefault;

/**
 * HeroTestimonials Shared Slice
 *
 * - **API ID**: `hero_testimonials`
 * - **Description**: HeroTestimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTestimonialsSlice = prismic.SharedSlice<
  "hero_testimonials",
  HeroTestimonialsSliceVariation
>;

/**
 * Item in *LinkSection → Default → Primary → List*
 */
export interface LinkSectionSliceDefaultPrimaryTreatmentsItem {
  /**
   * Title field in *LinkSection → Default → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.default.primary.treatments[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *LinkSection → Default → Primary → List*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.default.primary.treatments[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *LinkSection → dropdown list → Primary → List*
 */
export interface LinkSectionSliceDropdownListPrimaryTreatmentsItem {
  /**
   * question field in *LinkSection → dropdown list → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: add a common question
   * - **API ID Path**: link_section.dropdownList.primary.treatments[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Link field in *LinkSection → dropdown list → Primary → List*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.dropdownList.primary.treatments[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *LinkSection → Pricing list → Primary → List*
 */
export interface LinkSectionSlicePricingListPrimaryTreatmentsItem {
  /**
   * Treatment field in *LinkSection → Pricing list → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.pricingList.primary.treatments[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Cost field in *LinkSection → Pricing list → Primary → List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.pricingList.primary.treatments[].cost
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cost: prismic.KeyTextField;
}

/**
 * Primary content in *LinkSection → Default → Primary*
 */
export interface LinkSectionSliceDefaultPrimary {
  /**
   * Title field in *LinkSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * List field in *LinkSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.default.primary.treatments[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  treatments: prismic.GroupField<
    Simplify<LinkSectionSliceDefaultPrimaryTreatmentsItem>
  >;
}

/**
 * Default variation for LinkSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *LinkSection → dropdown list → Primary*
 */
export interface LinkSectionSliceDropdownListPrimary {
  /**
   * title field in *LinkSection → dropdown list → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.dropdownList.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * List field in *LinkSection → dropdown list → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.dropdownList.primary.treatments[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  treatments: prismic.GroupField<
    Simplify<LinkSectionSliceDropdownListPrimaryTreatmentsItem>
  >;
}

/**
 * dropdown list variation for LinkSection Slice
 *
 * - **API ID**: `dropdownList`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSectionSliceDropdownList = prismic.SharedSliceVariation<
  "dropdownList",
  Simplify<LinkSectionSliceDropdownListPrimary>,
  never
>;

/**
 * Primary content in *LinkSection → Pricing list → Primary*
 */
export interface LinkSectionSlicePricingListPrimary {
  /**
   * Title field in *LinkSection → Pricing list → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.pricingList.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * List field in *LinkSection → Pricing list → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.pricingList.primary.treatments[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  treatments: prismic.GroupField<
    Simplify<LinkSectionSlicePricingListPrimaryTreatmentsItem>
  >;
}

/**
 * Pricing list variation for LinkSection Slice
 *
 * - **API ID**: `pricingList`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSectionSlicePricingList = prismic.SharedSliceVariation<
  "pricingList",
  Simplify<LinkSectionSlicePricingListPrimary>,
  never
>;

/**
 * Slice variation for *LinkSection*
 */
type LinkSectionSliceVariation =
  | LinkSectionSliceDefault
  | LinkSectionSliceDropdownList
  | LinkSectionSlicePricingList;

/**
 * LinkSection Shared Slice
 *
 * - **API ID**: `link_section`
 * - **Description**: LinkSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSectionSlice = prismic.SharedSlice<
  "link_section",
  LinkSectionSliceVariation
>;

/**
 * Primary content in *LocationSlice → Default → Primary*
 */
export interface LocationSliceSliceDefaultPrimary {
  /**
   * Location field in *LocationSlice → Default → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: location_slice.default.primary.location
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  location: prismic.GeoPointField;
}

/**
 * Default variation for LocationSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LocationSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LocationSlice*
 */
type LocationSliceSliceVariation = LocationSliceSliceDefault;

/**
 * LocationSlice Shared Slice
 *
 * - **API ID**: `location_slice`
 * - **Description**: LocationSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationSliceSlice = prismic.SharedSlice<
  "location_slice",
  LocationSliceSliceVariation
>;

/**
 * Item in *OurTeamSlice → Default → Primary → Add Staff *
 */
export interface OurTeamSliceSliceDefaultPrimaryAddStaffItem {
  /**
   * Image field in *OurTeamSlice → Default → Primary → Add Staff *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *OurTeamSlice → Default → Primary → Add Staff *
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Occupation field in *OurTeamSlice → Default → Primary → Add Staff *
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[].occupation
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  occupation: prismic.SelectField<"Tannlæknir" | "Aðstoðarmaður Tannlæknis">;

  /**
   * Workplace field in *OurTeamSlice → Default → Primary → Add Staff *
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[].workplace
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  workplace: prismic.SelectField<"Reykjavík" | "Selfoss" | "Hella">;

  /**
   * Email field in *OurTeamSlice → Default → Primary → Add Staff *
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

/**
 * Primary content in *OurTeamSlice → Default → Primary*
 */
export interface OurTeamSliceSliceDefaultPrimary {
  /**
   * Title field in *OurTeamSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *OurTeamSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Add Staff  field in *OurTeamSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  add_staff: prismic.GroupField<
    Simplify<OurTeamSliceSliceDefaultPrimaryAddStaffItem>
  >;
}

/**
 * Default variation for OurTeamSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurTeamSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurTeamSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurTeamSlice*
 */
type OurTeamSliceSliceVariation = OurTeamSliceSliceDefault;

/**
 * OurTeamSlice Shared Slice
 *
 * - **API ID**: `our_team_slice`
 * - **Description**: OurTeamSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurTeamSliceSlice = prismic.SharedSlice<
  "our_team_slice",
  OurTeamSliceSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *SideBySideInfo → Illustration Left, Text Right → Primary → Information Blocks*
 */
export interface SideBySideInfoSliceIllustrationLeftTextRightPrimaryInfoGroupItem {
  /**
   * Heading field in *SideBySideInfo → Illustration Left, Text Right → Primary → Information Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_info.illustration_left_text_right.primary.info_group[].heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *SideBySideInfo → Illustration Left, Text Right → Primary → Information Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_info.illustration_left_text_right.primary.info_group[].content
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  content: prismic.KeyTextField;
}

/**
 * Primary content in *SideBySideInfo → Illustration Left, Text Right → Primary*
 */
export interface SideBySideInfoSliceIllustrationLeftTextRightPrimary {
  /**
   * Title field in *SideBySideInfo → Illustration Left, Text Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_info.illustration_left_text_right.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Illustration field in *SideBySideInfo → Illustration Left, Text Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_info.illustration_left_text_right.primary.illustration
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  illustration: prismic.ImageField<never>;

  /**
   * Information Blocks field in *SideBySideInfo → Illustration Left, Text Right → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_info.illustration_left_text_right.primary.info_group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  info_group: prismic.GroupField<
    Simplify<SideBySideInfoSliceIllustrationLeftTextRightPrimaryInfoGroupItem>
  >;
}

/**
 * Illustration Left, Text Right variation for SideBySideInfo Slice
 *
 * - **API ID**: `illustration_left_text_right`
 * - **Description**: Displays an illustration on the left and structured info (title, description, details) on the right.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SideBySideInfoSliceIllustrationLeftTextRight =
  prismic.SharedSliceVariation<
    "illustration_left_text_right",
    Simplify<SideBySideInfoSliceIllustrationLeftTextRightPrimary>,
    never
  >;

/**
 * Slice variation for *SideBySideInfo*
 */
type SideBySideInfoSliceVariation =
  SideBySideInfoSliceIllustrationLeftTextRight;

/**
 * SideBySideInfo Shared Slice
 *
 * - **API ID**: `side_by_side_info`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SideBySideInfoSlice = prismic.SharedSlice<
  "side_by_side_info",
  SideBySideInfoSliceVariation
>;

/**
 * Primary content in *TestimonialAbout → Default → Primary*
 */
export interface TestimonialAboutSliceDefaultPrimary {
  /**
   * Title field in *TestimonialAbout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_about.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for TestimonialAbout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialAboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialAboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialAbout*
 */
type TestimonialAboutSliceVariation = TestimonialAboutSliceDefault;

/**
 * TestimonialAbout Shared Slice
 *
 * - **API ID**: `testimonial_about`
 * - **Description**: TestimonialAbout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialAboutSlice = prismic.SharedSlice<
  "testimonial_about",
  TestimonialAboutSliceVariation
>;

/**
 * Primary content in *TitleAndRichText → Default → Primary*
 */
export interface TitleAndRichTextSliceDefaultPrimary {
  /**
   * Title field in *TitleAndRichText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_rich_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *TitleAndRichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TitleAndRichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleAndRichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleAndRichTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TitleAndRichText → Title → Primary*
 */
export interface TitleAndRichTextSliceTitlePrimary {
  /**
   * Title field in *TitleAndRichText → Title → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_rich_text.title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Title variation for TitleAndRichText Slice
 *
 * - **API ID**: `title`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleAndRichTextSliceTitle = prismic.SharedSliceVariation<
  "title",
  Simplify<TitleAndRichTextSliceTitlePrimary>,
  never
>;

/**
 * Primary content in *TitleAndRichText → heading and text → Primary*
 */
export interface TitleAndRichTextSliceHeadingAndTextPrimary {
  /**
   * Title field in *TitleAndRichText → heading and text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_rich_text.headingAndText.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *TitleAndRichText → heading and text → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_rich_text.headingAndText.primary.text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * heading and text variation for TitleAndRichText Slice
 *
 * - **API ID**: `headingAndText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleAndRichTextSliceHeadingAndText = prismic.SharedSliceVariation<
  "headingAndText",
  Simplify<TitleAndRichTextSliceHeadingAndTextPrimary>,
  never
>;

/**
 * Slice variation for *TitleAndRichText*
 */
type TitleAndRichTextSliceVariation =
  | TitleAndRichTextSliceDefault
  | TitleAndRichTextSliceTitle
  | TitleAndRichTextSliceHeadingAndText;

/**
 * TitleAndRichText Shared Slice
 *
 * - **API ID**: `title_and_rich_text`
 * - **Description**: TitleAndRichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleAndRichTextSlice = prismic.SharedSlice<
  "title_and_rich_text",
  TitleAndRichTextSliceVariation
>;

/**
 * Primary content in *TreatmentHero → Default → Primary*
 */
export interface TreatmentHeroSliceDefaultPrimary {
  /**
   * Title field in *TreatmentHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *TreatmentHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *TreatmentHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TreatmentHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TreatmentHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TreatmentHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TreatmentHero*
 */
type TreatmentHeroSliceVariation = TreatmentHeroSliceDefault;

/**
 * TreatmentHero Shared Slice
 *
 * - **API ID**: `treatment_hero`
 * - **Description**: TreatmentHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TreatmentHeroSlice = prismic.SharedSlice<
  "treatment_hero",
  TreatmentHeroSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ArticleArchieveDocument,
      ArticleArchieveDocumentData,
      ArticleArchieveDocumentDataSlicesSlice,
      ArticlePostsDocument,
      ArticlePostsDocumentData,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataQuickLinksItem,
      FooterDocumentDataContactInfoItem,
      FooterDocumentDataSocialsItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataNavlinksItem,
      NavbarDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      TestimonialCardsDocument,
      TestimonialCardsDocumentData,
      TreatmentBlogDocument,
      TreatmentBlogDocumentData,
      TreatmentBlogDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternateGridSlice,
      AlternateGridSliceDefaultPrimary,
      AlternateGridSliceImageLeftPrimary,
      AlternateGridSliceTitleAndButtonPrimary,
      AlternateGridSliceVariation,
      AlternateGridSliceDefault,
      AlternateGridSliceImageLeft,
      AlternateGridSliceTitleAndButton,
      BannerSliceSlice,
      BannerSliceSliceDefaultPrimary,
      BannerSliceSliceVariation,
      BannerSliceSliceDefault,
      FormSlice,
      FormSliceDefaultPrimary,
      FormSliceVariation,
      FormSliceDefault,
      HeroReviewSlice,
      HeroReviewSliceDefaultPrimaryReviewCardsItem,
      HeroReviewSliceDefaultPrimary,
      HeroReviewSliceVariation,
      HeroReviewSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceImageLeftAndTextRightPrimary,
      HeroSliceSliceImageTopTextBelowPrimary,
      HeroSliceSliceImageBottomTextTopPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      HeroSliceSliceImageLeftAndTextRight,
      HeroSliceSliceImageTopTextBelow,
      HeroSliceSliceImageBottomTextTop,
      HeroTestimonialsSlice,
      HeroTestimonialsSliceDefaultPrimary,
      HeroTestimonialsSliceVariation,
      HeroTestimonialsSliceDefault,
      LinkSectionSlice,
      LinkSectionSliceDefaultPrimaryTreatmentsItem,
      LinkSectionSliceDefaultPrimary,
      LinkSectionSliceDropdownListPrimaryTreatmentsItem,
      LinkSectionSliceDropdownListPrimary,
      LinkSectionSlicePricingListPrimaryTreatmentsItem,
      LinkSectionSlicePricingListPrimary,
      LinkSectionSliceVariation,
      LinkSectionSliceDefault,
      LinkSectionSliceDropdownList,
      LinkSectionSlicePricingList,
      LocationSliceSlice,
      LocationSliceSliceDefaultPrimary,
      LocationSliceSliceVariation,
      LocationSliceSliceDefault,
      OurTeamSliceSlice,
      OurTeamSliceSliceDefaultPrimaryAddStaffItem,
      OurTeamSliceSliceDefaultPrimary,
      OurTeamSliceSliceVariation,
      OurTeamSliceSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SideBySideInfoSlice,
      SideBySideInfoSliceIllustrationLeftTextRightPrimaryInfoGroupItem,
      SideBySideInfoSliceIllustrationLeftTextRightPrimary,
      SideBySideInfoSliceVariation,
      SideBySideInfoSliceIllustrationLeftTextRight,
      TestimonialAboutSlice,
      TestimonialAboutSliceDefaultPrimary,
      TestimonialAboutSliceVariation,
      TestimonialAboutSliceDefault,
      TitleAndRichTextSlice,
      TitleAndRichTextSliceDefaultPrimary,
      TitleAndRichTextSliceTitlePrimary,
      TitleAndRichTextSliceHeadingAndTextPrimary,
      TitleAndRichTextSliceVariation,
      TitleAndRichTextSliceDefault,
      TitleAndRichTextSliceTitle,
      TitleAndRichTextSliceHeadingAndText,
      TreatmentHeroSlice,
      TreatmentHeroSliceDefaultPrimary,
      TreatmentHeroSliceVariation,
      TreatmentHeroSliceDefault,
    };
  }
}
