// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *footer → Quick Links*
 */
export interface FooterDocumentDataQuickLinksItem {
  /**
   * Link field in *footer → Quick Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.quick_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *footer → Contact Info*
 */
export interface FooterDocumentDataContactInfoItem {
  /**
   * Info field in *footer → Contact Info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Gmail, Location, Phone Number, Etc
   * - **API ID Path**: footer.contact_info[].info
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  info: prismic.KeyTextField;
}

/**
 * Item in *footer → Socials*
 */
export interface FooterDocumentDataSocialsItem {
  /**
   * Social Icon field in *footer → Socials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[].social_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_icon: prismic.ImageField<never>;
}

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Quick Links field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.quick_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  quick_links: prismic.GroupField<Simplify<FooterDocumentDataQuickLinksItem>>;

  /**
   * Contact Info field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact_info[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  contact_info: prismic.GroupField<Simplify<FooterDocumentDataContactInfoItem>>;

  /**
   * Socials field in *footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.socials[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  socials: prismic.GroupField<Simplify<FooterDocumentDataSocialsItem>>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | TitleAndRichTextSlice
  | HeroReviewSlice
  | HeroTestimonialsSlice
  | HeroSliceSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type MedferdirDocumentDataSlicesSlice =
  | TitleAndRichTextSlice
  | TreatmentHeroSlice;

/**
 * Content for Medferdir documents
 */
interface MedferdirDocumentData {
  /**
   * Title field in *Medferdir*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: medferdir.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Button field in *Medferdir*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: medferdir.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Slice Zone field in *Medferdir*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: medferdir.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MedferdirDocumentDataSlicesSlice>;
}

/**
 * Medferdir document from Prismic
 *
 * - **API ID**: `medferdir`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MedferdirDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MedferdirDocumentData>,
    "medferdir",
    Lang
  >;

/**
 * Item in *Nav → Navlinks*
 */
export interface NavbarDocumentDataNavlinksItem {
  /**
   * Link field in *Nav → Navlinks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navlinks[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type NavbarDocumentDataSlicesSlice = LinkSectionSlice;

/**
 * Content for Nav documents
 */
interface NavbarDocumentData {
  /**
   * Logo field in *Nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Search icon field in *Nav*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.search_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  search_icon: prismic.ImageField<never>;

  /**
   * Navlinks field in *Nav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.navlinks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navlinks: prismic.GroupField<Simplify<NavbarDocumentDataNavlinksItem>>;

  /**
   * Slice Zone field in *Nav*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: navbar.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavbarDocumentDataSlicesSlice>;
}

/**
 * Nav document from Prismic
 *
 * - **API ID**: `navbar`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavbarDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavbarDocumentData>,
    "navbar",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | LinkSectionSlice
  | OurTeamSliceSlice
  | AlternateGridSlice
  | LocationSliceSlice
  | TitleAndRichTextSlice
  | HeroReviewSlice
  | HeroTestimonialsSlice
  | HeroSliceSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Testimonial title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.testimonial_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  testimonial_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Testimonial Cards documents
 */
interface TestimonialCardsDocumentData {
  /**
   * image field in *Testimonial Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Testimonial Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Testimonial Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * isButton field in *Testimonial Cards*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: testimonial_cards.isbutton
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  isbutton: prismic.BooleanField;

  /**
   * Button field in *Testimonial Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_cards.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Testimonial Cards document from Prismic
 *
 * - **API ID**: `testimonial_cards`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialCardsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestimonialCardsDocumentData>,
    "testimonial_cards",
    Lang
  >;

type TreatmentBlogDocumentDataSlicesSlice =
  | TitleAndRichTextSlice
  | HeroSliceSlice;

/**
 * Content for Treatment blog documents
 */
interface TreatmentBlogDocumentData {
  /**
   * Title field in *Treatment blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_blog.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Treatment blog*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_blog.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TreatmentBlogDocumentDataSlicesSlice> /**
   * Meta Title field in *Treatment blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: treatment_blog.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Treatment blog*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: treatment_blog.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Treatment blog*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_blog.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Treatment blog document from Prismic
 *
 * - **API ID**: `treatment_blog`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TreatmentBlogDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TreatmentBlogDocumentData>,
    "treatment_blog",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HomepageDocument
  | MedferdirDocument
  | NavbarDocument
  | PageDocument
  | TestimonialCardsDocument
  | TreatmentBlogDocument;

/**
 * Primary content in *AlternateGrid → Default → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
  /**
   * Image field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Body field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternateGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AlternateGrid → Image Left → Primary*
 */
export interface AlternateGridSliceImageLeftPrimary {
  /**
   * Image field in *AlternateGrid → Image Left → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageLeft.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Body field in *AlternateGrid → Image Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageLeft.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Image Left variation for AlternateGrid Slice
 *
 * - **API ID**: `imageLeft`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSliceImageLeft = prismic.SharedSliceVariation<
  "imageLeft",
  Simplify<AlternateGridSliceImageLeftPrimary>,
  never
>;

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation =
  | AlternateGridSliceDefault
  | AlternateGridSliceImageLeft;

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AlternateGridSlice = prismic.SharedSlice<
  "alternate_grid",
  AlternateGridSliceVariation
>;

/**
 * Item in *HeroReview → Default → Primary → Review Cards*
 */
export interface HeroReviewSliceDefaultPrimaryReviewCardsItem {
  /**
   * Review Text field in *HeroReview → Default → Primary → Review Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_review.default.primary.review_cards[].review_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  review_text: prismic.KeyTextField;

  /**
   * Reviewers Name field in *HeroReview → Default → Primary → Review Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_review.default.primary.review_cards[].reviewers_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reviewers_name: prismic.KeyTextField;

  /**
   * Card Color field in *HeroReview → Default → Primary → Review Cards*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_review.default.primary.review_cards[].card_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  card_color: prismic.SelectField<"Purple " | "Pink" | "Green" | "Yellow">;
}

/**
 * Primary content in *HeroReview → Default → Primary*
 */
export interface HeroReviewSliceDefaultPrimary {
  /**
   * Title field in *HeroReview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_review.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Review Cards field in *HeroReview → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_review.default.primary.review_cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  review_cards: prismic.GroupField<
    Simplify<HeroReviewSliceDefaultPrimaryReviewCardsItem>
  >;
}

/**
 * Default variation for HeroReview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroReviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroReviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroReview*
 */
type HeroReviewSliceVariation = HeroReviewSliceDefault;

/**
 * HeroReview Shared Slice
 *
 * - **API ID**: `hero_review`
 * - **Description**: HeroReview
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroReviewSlice = prismic.SharedSlice<
  "hero_review",
  HeroReviewSliceVariation
>;

/**
 * Primary content in *HeroSlice → Default → Primary*
 */
export interface HeroSliceSliceDefaultPrimary {
  /**
   * Hero Video field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.hero_video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  hero_video: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Logo field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * CTA Button field in *HeroSlice → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * Default variation for HeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSlice → image left and text right → Primary*
 */
export interface HeroSliceSliceImageLeftAndTextRightPrimary {
  /**
   * Image field in *HeroSlice → image left and text right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageLeftAndTextRight.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *HeroSlice → image left and text right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageLeftAndTextRight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *HeroSlice → image left and text right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageLeftAndTextRight.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * CTA Button field in *HeroSlice → image left and text right → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_slice.imageLeftAndTextRight.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * image left and text right variation for HeroSlice Slice
 *
 * - **API ID**: `imageLeftAndTextRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSliceImageLeftAndTextRight = prismic.SharedSliceVariation<
  "imageLeftAndTextRight",
  Simplify<HeroSliceSliceImageLeftAndTextRightPrimary>,
  never
>;

/**
 * Slice variation for *HeroSlice*
 */
type HeroSliceSliceVariation =
  | HeroSliceSliceDefault
  | HeroSliceSliceImageLeftAndTextRight;

/**
 * HeroSlice Shared Slice
 *
 * - **API ID**: `hero_slice`
 * - **Description**: HeroSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceSlice = prismic.SharedSlice<
  "hero_slice",
  HeroSliceSliceVariation
>;

/**
 * Primary content in *HeroTestimonials → Default → Primary*
 */
export interface HeroTestimonialsSliceDefaultPrimary {
  /**
   * Title field in *HeroTestimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for HeroTestimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroTestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroTestimonials*
 */
type HeroTestimonialsSliceVariation = HeroTestimonialsSliceDefault;

/**
 * HeroTestimonials Shared Slice
 *
 * - **API ID**: `hero_testimonials`
 * - **Description**: HeroTestimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroTestimonialsSlice = prismic.SharedSlice<
  "hero_testimonials",
  HeroTestimonialsSliceVariation
>;

/**
 * Item in *LinkSection → Default → Primary → Treatments*
 */
export interface LinkSectionSliceDefaultPrimaryTreatmentsItem {
  /**
   * Title field in *LinkSection → Default → Primary → Treatments*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.default.primary.treatments[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *LinkSection → Default → Primary → Treatments*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.default.primary.treatments[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Primary content in *LinkSection → Default → Primary*
 */
export interface LinkSectionSliceDefaultPrimary {
  /**
   * Treatments field in *LinkSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: link_section.default.primary.treatments[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  treatments: prismic.GroupField<
    Simplify<LinkSectionSliceDefaultPrimaryTreatmentsItem>
  >;
}

/**
 * Default variation for LinkSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinkSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LinkSection*
 */
type LinkSectionSliceVariation = LinkSectionSliceDefault;

/**
 * LinkSection Shared Slice
 *
 * - **API ID**: `link_section`
 * - **Description**: LinkSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinkSectionSlice = prismic.SharedSlice<
  "link_section",
  LinkSectionSliceVariation
>;

/**
 * Primary content in *LocationSlice → Default → Primary*
 */
export interface LocationSliceSliceDefaultPrimary {
  /**
   * Location field in *LocationSlice → Default → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: location_slice.default.primary.location
   * - **Documentation**: https://prismic.io/docs/field#geopoint
   */
  location: prismic.GeoPointField;
}

/**
 * Default variation for LocationSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LocationSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LocationSlice*
 */
type LocationSliceSliceVariation = LocationSliceSliceDefault;

/**
 * LocationSlice Shared Slice
 *
 * - **API ID**: `location_slice`
 * - **Description**: LocationSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationSliceSlice = prismic.SharedSlice<
  "location_slice",
  LocationSliceSliceVariation
>;

/**
 * Item in *OurTeamSlice → Default → Primary → Add Staff *
 */
export interface OurTeamSliceSliceDefaultPrimaryAddStaffItem {
  /**
   * Image field in *OurTeamSlice → Default → Primary → Add Staff *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *OurTeamSlice → Default → Primary → Add Staff *
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Occupation field in *OurTeamSlice → Default → Primary → Add Staff *
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[].occupation
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  occupation: prismic.SelectField<"Tannlæknir" | "Aðstoðarmaður Tannlæknis">;

  /**
   * Workplace field in *OurTeamSlice → Default → Primary → Add Staff *
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[].workplace
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  workplace: prismic.SelectField<"Reykjavík" | "Selfoss" | "Hella">;

  /**
   * Email field in *OurTeamSlice → Default → Primary → Add Staff *
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[].email
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;
}

/**
 * Primary content in *OurTeamSlice → Default → Primary*
 */
export interface OurTeamSliceSliceDefaultPrimary {
  /**
   * Title field in *OurTeamSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *OurTeamSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Add Staff  field in *OurTeamSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team_slice.default.primary.add_staff[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  add_staff: prismic.GroupField<
    Simplify<OurTeamSliceSliceDefaultPrimaryAddStaffItem>
  >;
}

/**
 * Default variation for OurTeamSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurTeamSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurTeamSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OurTeamSlice*
 */
type OurTeamSliceSliceVariation = OurTeamSliceSliceDefault;

/**
 * OurTeamSlice Shared Slice
 *
 * - **API ID**: `our_team_slice`
 * - **Description**: OurTeamSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurTeamSliceSlice = prismic.SharedSlice<
  "our_team_slice",
  OurTeamSliceSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *TitleAndRichText → Default → Primary*
 */
export interface TitleAndRichTextSliceDefaultPrimary {
  /**
   * Title field in *TitleAndRichText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_rich_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *TitleAndRichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TitleAndRichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleAndRichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleAndRichTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TitleAndRichText → Title → Primary*
 */
export interface TitleAndRichTextSliceTitlePrimary {
  /**
   * Title field in *TitleAndRichText → Title → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_rich_text.title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Title variation for TitleAndRichText Slice
 *
 * - **API ID**: `title`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleAndRichTextSliceTitle = prismic.SharedSliceVariation<
  "title",
  Simplify<TitleAndRichTextSliceTitlePrimary>,
  never
>;

/**
 * Slice variation for *TitleAndRichText*
 */
type TitleAndRichTextSliceVariation =
  | TitleAndRichTextSliceDefault
  | TitleAndRichTextSliceTitle;

/**
 * TitleAndRichText Shared Slice
 *
 * - **API ID**: `title_and_rich_text`
 * - **Description**: TitleAndRichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleAndRichTextSlice = prismic.SharedSlice<
  "title_and_rich_text",
  TitleAndRichTextSliceVariation
>;

/**
 * Primary content in *TreatmentHero → Default → Primary*
 */
export interface TreatmentHeroSliceDefaultPrimary {
  /**
   * Title field in *TreatmentHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *TreatmentHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Image field in *TreatmentHero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for TreatmentHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TreatmentHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TreatmentHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TreatmentHero*
 */
type TreatmentHeroSliceVariation = TreatmentHeroSliceDefault;

/**
 * TreatmentHero Shared Slice
 *
 * - **API ID**: `treatment_hero`
 * - **Description**: TreatmentHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TreatmentHeroSlice = prismic.SharedSlice<
  "treatment_hero",
  TreatmentHeroSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataQuickLinksItem,
      FooterDocumentDataContactInfoItem,
      FooterDocumentDataSocialsItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      MedferdirDocument,
      MedferdirDocumentData,
      MedferdirDocumentDataSlicesSlice,
      NavbarDocument,
      NavbarDocumentData,
      NavbarDocumentDataNavlinksItem,
      NavbarDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      TestimonialCardsDocument,
      TestimonialCardsDocumentData,
      TreatmentBlogDocument,
      TreatmentBlogDocumentData,
      TreatmentBlogDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternateGridSlice,
      AlternateGridSliceDefaultPrimary,
      AlternateGridSliceImageLeftPrimary,
      AlternateGridSliceVariation,
      AlternateGridSliceDefault,
      AlternateGridSliceImageLeft,
      HeroReviewSlice,
      HeroReviewSliceDefaultPrimaryReviewCardsItem,
      HeroReviewSliceDefaultPrimary,
      HeroReviewSliceVariation,
      HeroReviewSliceDefault,
      HeroSliceSlice,
      HeroSliceSliceDefaultPrimary,
      HeroSliceSliceImageLeftAndTextRightPrimary,
      HeroSliceSliceVariation,
      HeroSliceSliceDefault,
      HeroSliceSliceImageLeftAndTextRight,
      HeroTestimonialsSlice,
      HeroTestimonialsSliceDefaultPrimary,
      HeroTestimonialsSliceVariation,
      HeroTestimonialsSliceDefault,
      LinkSectionSlice,
      LinkSectionSliceDefaultPrimaryTreatmentsItem,
      LinkSectionSliceDefaultPrimary,
      LinkSectionSliceVariation,
      LinkSectionSliceDefault,
      LocationSliceSlice,
      LocationSliceSliceDefaultPrimary,
      LocationSliceSliceVariation,
      LocationSliceSliceDefault,
      OurTeamSliceSlice,
      OurTeamSliceSliceDefaultPrimaryAddStaffItem,
      OurTeamSliceSliceDefaultPrimary,
      OurTeamSliceSliceVariation,
      OurTeamSliceSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      TitleAndRichTextSlice,
      TitleAndRichTextSliceDefaultPrimary,
      TitleAndRichTextSliceTitlePrimary,
      TitleAndRichTextSliceVariation,
      TitleAndRichTextSliceDefault,
      TitleAndRichTextSliceTitle,
      TreatmentHeroSlice,
      TreatmentHeroSliceDefaultPrimary,
      TreatmentHeroSliceVariation,
      TreatmentHeroSliceDefault,
    };
  }
}
