// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  hero_review: dynamic(() => import("./HeroReview")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  hero_testimonials: dynamic(() => import("./HeroTestimonials")),
  link_section: dynamic(() => import("./LinkSection")),
  location_slice: dynamic(() => import("./LocationSlice")),
  our_team_slice: dynamic(() => import("./OurTeamSlice")),
  rich_text: dynamic(() => import("./RichText")),
  title_and_rich_text: dynamic(() => import("./TitleAndRichText")),
  treatment_hero: dynamic(() => import("./TreatmentHero")),
};
